workflows:
  unity-android-build:
    name: Unity Android Build
    max_build_duration: 60
    environment:
      unity: "6000.0.33f1"
      android_signing:
        - goalstormarena # 👈 тут лише назва конфігурації з UI
      vars:
        GCLOUD_SERVICE_ACCOUNT_CREDENTIALS: $GOOGLE_PLAY_JSON

    scripts:
      - name: Debug env
        script: |
          echo "=== GOOGLE CREDS BEGIN ==="
          echo "$GOOGLE_PLAY_JSON"
          echo "=== GOOGLE CREDS END ==="
      - name: Build .aab with Unity
        script: |
          unity-editor -batchmode -quit -nographics -silent-crashes \
            -projectPath . \
            -executeMethod BuildScript.BuildAndroid

    artifacts:
      - build/app.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_JSON
        track: internal
