default_platform(:android)

platform :android do
  lane :promote_to_alpha do
    supply(
      json_key_data: ENV["GH_PERSONAL_TOKEN"],
      package_name: "com.goal.storm.arena",
      track: "alpha",
      version_code: 2,
      status: "completed"
    )
  end
end
