name: Promote Release to Alpha

on:
  workflow_dispatch:

jobs:
  promote-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Promote to Alpha
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: promote_to_alpha
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GH_PERSONAL_TOKEN }}
